jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - pwd
      - ls
      - sh ./alpine-minirootfs-download.sh
      - sh ./alpine-minirootfs-docker-build.sh

