jobs:
  build:
    docker:
      - image: docker:stable-git

    working_directory: /home/ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: sh ./alpine-minirootfs-download.sh
      - run: sh ./alpine-minirootfs-docker-build.sh
      - run: ls
      - run: git add .
      - run: git config --global user.email $CIRCLE_USERNAME
      - run: git config --global user.name "CircleCI"
      - run: git commit -m "[ci skip] CircleCI rootfs autogeneration"
      - run: git push origin master
      - run: echo Build has ended sucesfully!
      - run: curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/ogomez/arm32v7-alpine/trigger/9a51eaac-d7a7-4acb-a335-93c68c87fead/
