jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/ubuntu
    steps:
      # command will execute in trusty container
      - checkout
      - setup_remote_docker
      - run: pwd

