jobs:
  build:
    docker:
      - image: docker:stable-git

    working_directory: /home/ubuntu
    steps:
      - checkout
      - run: sh ./install-packages.sh
      - setup_remote_docker
      - run: sh ./alpine-minirootfs-download.sh
      - run: ls -lah
      - run: sh ./alpine-dockerhub-build.sh
