jobs:
  build:
    docker:
      - image: docker:stable-git

    working_directory: /home/ubuntu
    steps:
      - checkout
      - run: apk add --update curl && \
      - setup_remote_docker
      - run: sh ./alpine-minirootfs-download.sh
      - run: sh ./alpine-minirootfs-docker-build.sh
      - run: ls
      - run: git add .
      - run: git config --global user.email $CIRCLE_USERNAME
      - run: git config --global user.name "CircleCI"
      - run: git commit -m "[ci skip] CircleCI rootfs autogeneration"
      - run: git push origin master
      - run: sh ./alpine-dockerhub-build.sh
