version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    working_directory: /home/ubuntu
    steps:
    # Code checkout
      - checkout
    # Installing build dependencies
      - run:
          name: Downloading build image dependencies
          command: sh ./scripts/install-packages.sh
    # Downloading Alpine
      - run:
          name: Find Alpine Latest version
          command: |
             bash ./scripts/minirootfs-download.sh
    # Bringing remote docker up
      - setup_remote_docker
    # Creating Arm32v7-Alpine image
      - run:
          name: Creating Arm32v7-Alpine image
          command: |
            source $HOME/.circlerc
            bash ./scripts/Arm32v7-Alpine-docker-build.sh
    # Running the docker container with qemu [Emulating Arm32v7]
      - run:
          name: Running the docker container with qemu [Emulating Arm32v7]
          command: sh ./scripts/Arm32v7-Alpine-docker-run.sh
    # Running the test within the running Arm32v7-Alpine container
      - run:
          name: Running the test within the running Arm32v7-Alpine container
          command: sh ./scripts/Arm32v7-Alpine-tests.sh
    # Push release folder, rootfs and signature to Github
    # Trigger the Dockehub.com remote build
      - run:
          name: Pushing release folder, rootfs and signature to github AND Dockerhub.com build trigger
          command: |
            source $HOME/.circlerc
            bash ./scripts/dockerhub-build.sh
          context: DOCKERHUBKEY
workflows:
  version: 2
  nightly:
    jobs:
     - build
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - master
