jobs:
  build:
    docker:
      - image: docker

    working_directory: /home/ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: sh ./alpine-minirootfs-download.sh
      - run: sh ./alpine-minirootfs-docker-build.sh
      - run: ls
      - run: git add .
      - run: git commit -m "[ci skip] CircleCI rootfs autogeneration"
      - run: git push origin master

