jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: ls
      - run: sh ./alpine-minirootfs-download.sh
      - run: sh ./alpine-minirootfs-docker-build.sh
