jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/
    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - run: pwd

